spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tripmanager?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true
    username: tripManager
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 데이터베이스 스키마 자동 업데이트를 사용하려면
    show-sql: true # SQL 쿼리를 콘솔에 출력하려면
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect # Mysql5.7 버전에 맞는 Hibernate dialect 사용
  servlet:
    multipart:
      maxFileSize: 20MB        # 파일 한 개당 사이즈
      maxRequestSize: 100MB    # 요청당 최대 파일 크기


server:
  port: 8090 # 스프링 부트 애플리케이션의 포트 설정
  servlet:
    encoding:
      charset: UTF-8
  
# 경로 매칭 전략 설정
mvc:
  pathmatch:
    matching-strategy: ANT_PATH_MATCHER
    
springdoc:
  show-version: true           # 문서에 애플리케이션 버전을 표시할지 여부
  show-common-errors: true     # 일반적인 오류 응답을 문서에 표시할지 여부
  packages-to-scan: tnew.manager.project  # 문서화할 대상 패키지를 지정        

  api-docs:
    path: /v3/api-docs          # OpenAPI JSON 엔드포인트의 경로

  swagger-ui:
    path: /swagger-ui.html      # Swagger UI의 경로
    enabled: true              # Swagger UI를 활성화
    disable-swagger-default-url: true  # 기본 Swagger UI URL 비활성화
   
# 파일 업로드 경로
productFileLocation: D:/Study/nas

# 리소스 업로드 경로
uploadPath: file:///D:/Study/nas 

